#!/bin/sh
### BEGIN INIT INFO
# Provides:       pyzbxagent $named
# Required-Start:
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Simple Zabbix agent for Maemo
### END INIT INFO

set +e   # Don't exit on error status

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/user/pyzbxagent/pyzbxagent.py
PIDFILE=/home/user/pyzbxagent/var/pyzbxagent.pid
NAME=pyzbxagent
DESC="Simple Zabbix Agent"
OPTS="-d"

test -x $DAEMON || exit 0

case "$1" in
    start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --user user --quiet --pidfile $PIDFILE --exec $DAEMON -- $OPTS
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --user user --quiet --pidfile $PIDFILE --name $NAME
        echo "$NAME."
        ;;
  restart|force-reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac

exit 0

