#!/bin/sh
### BEGIN INIT INFO
# Provides:       pyzbxagent $named
# Required-Start:
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Simple Zabbix agent for Maemo
### END INIT INFO

set +e   # Don't exit on error status

USER=user
ROOT=/home/user/pyzbxagent
DAEMON=$ROOT/pyzbxagent.py
PIDFILE=$ROOT/var/pyzbxagent.pid
NAME=pyzbxagent.py
DESC="Simple Zabbix Agent"
OPTS="-d"

test -x $DAEMON || exit 0

case "$1" in
    start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --user $USER --quiet --pidfile $PIDFILE --exec $DAEMON -- $OPTS
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --user $USER --quiet --pidfile $PIDFILE --name $NAME
        echo "$NAME."
        ;;
  restart|force-reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac

exit 0

